# Generated by Django 4.2 on 2024-09-03 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssis', '0002_alter_resource_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_path',
            field=models.FileField(upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uploadedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_resources', to=settings.AUTH_USER_MODEL),
        ),
    ]
