# Generated by Django 4.2 on 2024-09-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssis', '0003_alter_resource_file_path_alter_resource_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_path',
            field=models.FileField(upload_to='media/'),
        ),
    ]
