# Generated by Django 4.2 on 2024-09-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssis', '0004_alter_resource_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_path',
            field=models.FileField(upload_to=''),
        ),
    ]
