# Generated by Django 4.2 on 2024-09-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssis', '0005_alter_resource_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_path',
            field=models.FileField(upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='usertb',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photos/'),
        ),
    ]
