# Generated by Django 4.2 on 2024-09-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssis', '0006_alter_resource_file_path_alter_usertb_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumtb',
            name='title',
        ),
    ]
