# Generated by Django 4.2 on 2024-09-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssis', '0007_remove_forumtb_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtb',
            name='category',
            field=models.CharField(choices=[('academics', 'Academics'), ('psychosocials', 'Psychosocials'), ('groups', 'Groups')], default='academics', max_length=20),
        ),
    ]
