# Generated by Django 4.2 on 2024-09-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssis', '0008_forumtb_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttb',
            name='category',
            field=models.CharField(blank=True, choices=[('academics', 'Academics'), ('psychosocials', 'Psychosocials'), ('groups', 'Groups')], max_length=20, null=True),
        ),
    ]
