# Generated by Django 4.2 on 2024-09-09 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssis', '0010_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_user',
            name='user',
        ),
        migrations.AddField(
            model_name='notification_user',
            name='receiverID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='ssis.appointmentstb'),
        ),
        migrations.AddField(
            model_name='notification_user',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='ssis.appointmentstb'),
            preserve_default=False,
        ),
    ]
