# Generated by Django 4.2 on 2024-09-10 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssis', '0011_remove_notification_user_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_user',
            name='read',
        ),
        migrations.AlterField(
            model_name='notification_user',
            name='receiverID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification_user',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
